<a href="https://colab.research.google.com/github/raju1207/fake-news-detection/blob/main/fake_news_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
news_data = pd.read_csv("news.csv")
news_data

                                                    text  label
0      Gere faults Trump for blurring meaning of 'ref...      1
1      German parties start to find common ground in ...      1
2      Senate Democratic leader says Attorney General...      1
3      Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4       Trump Threw Mar-A-Lago Fundraiser For Woman A...      0
...                                                  ...    ...
45752   Heavily-Armed Man Claiming To Be Jesus Arrest...      0
45753  Evangelicals Across The Spectrum Are Clarifyin...      0
45754  Senators question Kaleo' $4,500 tag on opioid ...      1
45755   CNN Does NOT Hold Back; Completely Makes Fun ...      0
45756  U.S. judge throws out Texas voter ID law suppo...      1

[45757 rows x 2 columns]

In [8]:
news_data.head()

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [9]:
news_data.isnull()

        text  label
0      False  False
1      False  False
2      False  False
3      False  False
4      False  False
...      ...    ...
45752  False  False
45753  False  False
45754  False  False
45755  False  False
45756  False  False

[45757 rows x 2 columns]

In [13]:
news_data.shape

(45757, 2)

In [15]:
#Check for Missing Values (Null Values)

news_data.isnull().sum()

text     0
label    0
dtype: int64

In [16]:
news_data.dropna()

                                                    text  label
0      Gere faults Trump for blurring meaning of 'ref...      1
1      German parties start to find common ground in ...      1
2      Senate Democratic leader says Attorney General...      1
3      Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4       Trump Threw Mar-A-Lago Fundraiser For Woman A...      0
...                                                  ...    ...
45752   Heavily-Armed Man Claiming To Be Jesus Arrest...      0
45753  Evangelicals Across The Spectrum Are Clarifyin...      0
45754  Senators question Kaleo' $4,500 tag on opioid ...      1
45755   CNN Does NOT Hold Back; Completely Makes Fun ...      0
45756  U.S. judge throws out Texas voter ID law suppo...      1

[45757 rows x 2 columns]

In [17]:
news_data.duplicated().sum()

np.int64(0)